version: '3.9'
services:
  app:
    build: .
    image: maayanlab/songgame-app:0.0.1
    environment:
      - DATABASE_URL=$DATABASE_URL
      - AUTHORIZATION_HEADER=$AUTHORIZATION_HEADER
      - NODE_ENV=production
    ports:
      - 3000:3000
  db:
    build: db
    image: maayanlab/songgame-db:0.0.1
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
