version: '3.9'
services:
  app:
    build: .
    image: giacomomarino/songgame-app:0.0.1
    environment:
      - VITE_CLIENT_ID=$VITE_CLIENT_SECRET
      - VITE_CLIENT_SECRET=$VITE_CLIENT_SECRET
      - VITE_REDIRECT_URI=$VITE_REDIRECT_URI
      - VITE_SUPABASE_URL=$VITE_SUPABASE_URL
      - VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
      - DB_PASSWORD=$DB_PASSWORD
    ports:
      - 3000:3000
